// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2024, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;
import ballerina/test;

configurable http:BearerTokenConfig & readonly authConfig = ?;
ConnectionConfig config = {auth : authConfig};
Client baseClient = check new Client(config, serviceUrl = "https://api.intercom.io");

@test:Config {}
isolated function  testListHelpCenters() {
}

@test:Config {}
isolated function  testUpdateCompany() {
}

@test:Config {}
isolated function  testRetrieveACompanyById() {
}

@test:Config {}
isolated function  testDeleteCompany() {
}

@test:Config {}
isolated function  testListNewsItems() {
}

@test:Config {}
isolated function  testCreateNewsItem() {
}

@test:Config {}
isolated function  testUnarchiveContact() {
}

@test:Config {}
isolated function  testListTags() {
}

@test:Config {}
isolated function  testCreateTag() {
}

@test:Config {}
isolated function  testListCompaniesForAContact() {
}

@test:Config {}
isolated function  testAttachContactToACompany() {
}

@test:Config {}
isolated function  testDetachContactFromACompany() {
}

@test:Config {}
isolated function  testIdentifyAdmin() {
}

@test:Config {}
isolated function  testListSubscriptionsForAContact() {
}

@test:Config {}
isolated function  testAttachSubscriptionTypeToContact() {
}

@test:Config {}
isolated function  testListTicketTypes() {
}

@test:Config {}
isolated function  testCreateTicketType() {
}

@test:Config {}
isolated function  testAttachTagToTicket() {
}

@test:Config {}
isolated function  testListAdmins() {
}

@test:Config {}
isolated function  testUpdateContact() {
}

@test:Config {}
isolated function  testShowContact() {
}

@test:Config {}
isolated function  testDeleteContact() {
}

@test:Config {}
isolated function  testConvertConversationToTicket() {
}

@test:Config {}
isolated function  testSearchTickets() {
}

@test:Config {}
isolated function  testArchiveContact() {
}

@test:Config {}
isolated function  testUpdateNewsItem() {
}

@test:Config {}
isolated function  testRetrieveNewsItem() {
}

@test:Config {}
isolated function  testDeleteNewsItem() {
}

@test:Config {}
isolated function  testDetachTagFromContact() {
}

@test:Config {}
isolated function  testSearchArticles() {
}

@test:Config {}
isolated function  testUpdateDataAttribute() {
}

@test:Config {}
isolated function  testMergeContact() {
}

@test:Config {}
isolated function  testDetachContactFromConversation() {
}

@test:Config {}
isolated function  testListTeams() {
}

@test:Config {}
isolated function  testCreateTicket() {
}

@test:Config {}
isolated function  testRetrieveTeam() {
}

@test:Config {}
isolated function  testListAttachedSegmentsForCompanies() {
}

@test:Config {}
isolated function  testManageConversation() {
}

@test:Config {}
isolated function  testDetachTagFromConversation() {
}

@test:Config {}
isolated function  testListActivityLogs() {
}

@test:Config {}
isolated function  testUpdateTicket() {
}

@test:Config {}
isolated function  testGetTicket() {
}

@test:Config {}
isolated function  testListSegmentsForAContact() {
}

@test:Config {}
isolated function  testListSegments() {
}

@test:Config {}
isolated function  testFindTag() {
}

@test:Config {}
isolated function  testDeleteTag() {
}

@test:Config {}
isolated function  testScrollOverAllCompanies() {
}

@test:Config {}
isolated function  testRetrieveSegment() {
}

@test:Config {}
isolated function  testListNewsfeeds() {
}

@test:Config {}
isolated function  testUpdateTicketTypeAttribute() {
}

@test:Config {}
isolated function  testUpdateTicketType() {
}

@test:Config {}
isolated function  testGetTicketType() {
}

@test:Config {}
isolated function  testUpdateArticle() {
}

@test:Config {}
isolated function  testRetrieveArticle() {
}

@test:Config {}
isolated function  testDeleteArticle() {
}

@test:Config {}
isolated function  testLisDataAttributes() {
}

@test:Config {}
isolated function  testCreateDataAttribute() {
}

@test:Config {}
isolated function  testCreateTicketTypeAttribute() {
}

@test:Config {}
isolated function  testListArticles() {
}

@test:Config {}
isolated function  testCreateArticle() {
}

@test:Config {}
isolated function  testListContacts() {
}

@test:Config {}
isolated function  testCreateContact() {
}

@test:Config {}
isolated function  testListAllCompanies() {
}

@test:Config {}
isolated function  testGetDataExport() {
}

@test:Config {}
isolated function  testLisDataEvents() {
}

@test:Config {}
isolated function  testCreateDataEvent() {
}

@test:Config {}
isolated function  testRetrieveNewsfeed() {
}

@test:Config {}
isolated function  testListSubscriptionTypes() {
}

@test:Config {}
isolated function  testRetrieveNote() {
}

@test:Config {}
isolated function  testRetrieveCompany() {
}

@test:Config {}
isolated function  testCreateOrUpdateCompany() {
}

@test:Config {}
isolated function  testListAllCollections() {
}

@test:Config {}
isolated function  testCreateCollection() {
}

@test:Config {}
isolated function  testListTagsForAContact() {
}

@test:Config {}
isolated function  testAttachTagToContact() {
}

@test:Config {}
isolated function  testDownloadDataExport() {
}

@test:Config {}
isolated function  testAttachContactToConversation() {
}

@test:Config {}
isolated function  testCancelDataExport() {
}

@test:Config {}
isolated function  testListConversations() {
}

@test:Config {}
isolated function  testCreateConversation() {
}

@test:Config {}
isolated function  testAutoAssignConversation() {
}

@test:Config {}
isolated function  testListAttachedContacts() {
}

@test:Config {}
isolated function  testSearchContacts() {
}

@test:Config {}
isolated function  testCreatePhoneSwitch() {
}

@test:Config {}
isolated function  testSetAwayAdmin() {
}

@test:Config {}
isolated function  testUpdateConversation() {
}

@test:Config {}
isolated function  testRetrieveConversation() {
}

@test:Config {}
isolated function  testAttachTagToConversation() {
}

@test:Config {}
isolated function  testReplyConversation() {
}

@test:Config {}
isolated function  testRedactConversation() {
}

@test:Config {}
isolated function  testCreateDataExport() {
}

@test:Config {}
isolated function  testReplyTicket() {
}

@test:Config {}
isolated function  testDataEventSummaries() {
}

@test:Config {}
isolated function  testListLiveNewsfeedItems() {
}

@test:Config {}
isolated function  testDetachSubscriptionTypeToContact() {
}

@test:Config {}
isolated function  testConvertVisitor() {
}

@test:Config {}
isolated function  testDetachTagFromTicket() {
}

@test:Config {}
isolated function  testRetrieveAdmin() {
}

@test:Config {}
isolated function  testUpdateVisitor() {
}

@test:Config {}
isolated function  testRetrieveVisitorWithUserId() {
}

@test:Config {}
isolated function  testSearchConversations() {
}

@test:Config {}
isolated function  testListNotes() {
}

@test:Config {}
isolated function  testCreateNote() {
}

@test:Config {}
isolated function  testUpdateCollection() {
}

@test:Config {}
isolated function  testRetrieveCollection() {
}

@test:Config {}
isolated function  testDeleteCollection() {
}

@test:Config {}
isolated function  testRetrieveHelpCenter() {
}

@test:Config {}
isolated function  testCreateMessage() {
}
