[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "intercom"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = []
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-intercom"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
